apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: devops-tools
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"  # Redirect HTTP â†’ HTTPS
spec:
  ingressClassName: nginx       # Modern way to specify Ingress controller
  tls:
    - hosts:
        - jenkins.cambostack.codes
      secretName: jenkins-tls
  rules:
    - host: jenkins.cambostack.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins-service
                port:
                  number: 8080