
appName:
  app: nginx-prod
replicas: 5
container:
  name: nginx-cont
  image: nginx:latest
  port: 80
  env:
    - name: POSTGRES_USER
      value: pes-expo
    - name: POSTGRES_DB
      value: pes-store-prod
    - name: POSTGRES_PASSWORD
      value: pes@prod
affinity:   
  podAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - myapp
          topologyKey: kubernetes.io/hostname

  nodeaffinity:
    requiredduringschedulingignoredduringexecution:
      nodeselectorterms:
        - matchexpressions:
            - key: node-type
              operator: in
              values:
                - production
nodeSelector: 
  kubernetes.io/hostname: node5
  #disktype: ssd   
resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
